speedu/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('mainpage.urls')),
    path('', include('speedu_tutor.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

speedu_tutor/urls.py
from django.urls import path, include
from django.conf.urls import url

from . import views

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

    url('^serviceworker.js$', views.service_worker),
    url('^manifest.json$', views.manifest),

    path('tutor/', views.index, name='tutor'),
    path('offline/', views.offline),
    path('tutor/profile/', views.profile, name='profile'),

    path('tutor/tutorial/<int:pk>/', views.tutorial_detail, name='tutorial-detail'),   
]

speedu_tutor/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone

import os
from uuid import uuid4

def wrapper(instance, filename):
    ext = filename.split('.')[-1]
    now = timezone.now()
    filename = '{}_{}.{}'.format(uuid4().hex, now, ext)           
    return os.path.join('images/institutions', filename)

class Institution(models.Model):
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to=wrapper)

    def __str__(self):
        return self.name   
    

class Career(models.Model):
    name = models.CharField(max_length=100)
    institution = models.ManyToManyField(Institution)

    def __str__(self):
        return self.name

class Subject(models.Model):
    name = models.CharField(max_length=100)
    career = models.ManyToManyField(Career)

    def __str__(self):
        return self.name

class Student(models.Model):

    CHOICES_DOC_TYPE = [
        ('CC', 'Cédula de ciudadania'),
        ('TI', 'Tarjeta de identidad'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    doc_type = models.CharField(max_length=2, choices=CHOICES_DOC_TYPE)
    doc_number = models.CharField(max_length=10, unique=True)
    telefono = models.CharField(max_length=10, unique=True)
    semester = models.IntegerField()
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    career = models.ForeignKey(Career, on_delete=models.CASCADE)

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

class Tutor(models.Model):
    CHOICES_STATES = [
        ('V', 'En Verificación'),
        ('A', 'Aprobado'),
        ('R', 'Rechsazado'),
        ('I', 'Inactivo'),
    ]

    student = models.OneToOneField(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    score = models.FloatField()
    argument = models.TextField()
    state = models.CharField(max_length=1, choices=CHOICES_STATES, default='En Verificación')

    def __str__(self):
        return '{} {}'.format(self.student.user.first_name, self.student.user.last_name)

class Schedule(models.Model):
    CHOICES_DAYS = [
        ('lunes', 'Lunes'),
        ('martes', 'Martes'),
        ('miercoles', 'Miercoles'),
        ('jueves', 'Jueves'),
        ('viernes', 'Viernes'),
        ('sabado', 'Sabado'),
    ]
    
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE)
    day = models.CharField(max_length=10, choices=CHOICES_DAYS)
    hour_start = models.TimeField()
    hour_end = models.TimeField()

    def __str__(self):
        return '{} {}-{}'.format(self.day, self.hour_start, self.hour_end)

class Tutorial(models.Model):
    CHOICES_STATES = [
        ('0', 'Programada'),
        ('1', 'Termininada'),
    ]

    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)   
    semester = models.IntegerField()
    state = models.CharField(max_length=1, choices=CHOICES_STATES, default='Programada')

    def __str__(self):
        return '{}-{} Semester {}'.format(self.schedule.hour_start, self.schedule.hour_end, self.semester)
    
    def get_absolute_url(self):
        return reverse('tutorial-detail', args=[str(self.id)])

class Competitor(models.Model):
    tutorial = models.ForeignKey(Tutorial, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    attended_tutor = models.BooleanField()
    attended_student = models.BooleanField()

    def __str__(self):
        return '{} {}'.format(self.student.user.first_name, self.student.user.last_name)

speedu_tutor/forms.py
from django import forms

class LoginForm(forms.Form):
    email = forms.EmailField(label='Correo Electrónico', required=True)
    password = forms.CharField(label='Contraseña', required=True, widget=forms.PasswordInput)
    rememberme = forms.BooleanField(required=False)

class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(label='Contraseña actual', required=True, widget=forms.PasswordInput)
    new_password = forms.CharField(label='Nueva contraseña', required=True, widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='Confirme la contraseña', required=True, widget=forms.PasswordInput)

speedu_tutor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash

from . import app_settings
from .forms import LoginForm, ChangePasswordForm


def user_login(request):

    if request.user.is_authenticated:
        return redirect('tutor', permanent=True)

    user_invalid = False
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            rememberme = form.cleaned_data['rememberme']

            user = authenticate(username=email, password=password)
            if user is not None:
                login(request, user)
                if not rememberme:
                    request.session.set_expiry(900)

                return redirect('tutor', permanent=True)
            else:
                user_invalid = True                

    else:
        form = LoginForm()
    
    context = {
        'form': form,
        'user_invalid': user_invalid,
    }

    return render(request, 'speedu_tutor/auth/login.html', context=context)

def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('index', permanent=True)
    return redirect('tutor', permanent=True)

@login_required
def index(request):
    context = {
        'title': 'Inicio - SpeedU Tutor',
    }
    return render(request, 'speedu_tutor/index.html', context=context)

@login_required
def profile(request):
    context = {
        'title': '{} - SpeedU Tutor'.format(request.user.student),
    }

    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():

            current_password = form.cleaned_data['current_password']
            new_password = form.cleaned_data['new_password']
            confirm_password = form.cleaned_data['confirm_password']

            if new_password == confirm_password:
                if request.user.check_password(current_password):
                    request.user.set_password(new_password)
                    request.user.save()
                    update_session_auth_hash(request, request.user)
                    context['message'] = {
                        'text': 'La contraseña se actualizó correctamente.',
                        'type': 'success',
                    }
                else:
                    context['message'] = {
                        'text': 'La contraseña es incorrecta.',
                        'type': 'error',
                    }
            else:
                context['message'] = {
                    'text': 'Las contraseñas no coinciden.',
                    'type': 'error',
                }
        else:
            context['message'] = {
                'text': 'Formulario incorrecto.',
                'type': 'error'
            }
    else:
        form = ChangePasswordForm()
    
    context['form'] = form

    return render(request, 'speedu_tutor/profile.html', context=context)

@login_required
def tutorial_detail(request, pk):
    return render(request, 'speedu_tutor/index.html')

def offline(request):
    return render(request, 'speedu_tutor/layout.html', context={'title': 'Offline - SpeedU Tutor'})


def service_worker(request):
    response = HttpResponse(open(app_settings.PWA_SERVICE_WORKER_PATH).read(), content_type='application/javascript')
    return response

def manifest(request):
    return render(request, 'speedu_tutor/pwa/manifest.json')

speedu_tutor/templates/speedu_tutor/index.html
{% extends 'speedu_tutor/layout.html' %}

{% load static %}

{% block container%}
    <div class="row mt-0 mt-md-3">
        <div class="col-lg-4 col-md-5">
            <div class="user-block bg-dark">
                <div class="row row-condensed">
                    <div class="col-12">
                        <div class="user-info">
                            <div class="user-wrapper">
                                <div class="img-circle">
                                    <img src="{{ user.student.institution.image.url }}" alt="{{ user.student.institution }}" class="img">
                                </div>
                            </div>
                            <a href="{% url 'profile' %}" class="user-name h4">
                                <span>{{ user.first_name }} {{ user.last_name }}</span>
                            </a>
                            <span class="user-career">{{ user.student.career }}</span>
                        </div>
                    </div>
                </div>
                <div class="row row-condensed">
                    <div class="col-6">
                        <h4 class="text-white">{{ user.student.semester }}</h4>
                        <p class="item-data">Semestre</p>
                    </div>
                    <div class="col-6">
                        <h4 class="text-white">
                            {% if user.student.tutor and user.student.tutor.state == 'A' %}
                                Estd. Tutor
                            {% else %}
                                Estudiante
                            {% endif %}
                        </h4>
                        <p class="item-data">Rol</p>
                    </div>
                </div>
            </div>

            <div class="col-12 p-0">
                <div class="su-box-common no-padding">
                    <div id="slide-carousel-info" class="carousel slide" data-ride="carousel">                                   
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                    <div class="item-img">
                                        <img src="{% static 'mainpage/img/testimonial_img_3.png' %}" alt="">
                                    </div>   
                                    <div class="p-3">
                                        <p class="h4">¡Tips!</p>
                                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique ab rem nemo. Odio rem explicabo asperiores, maxime reiciendis vero ratione? Repudiandae animi doloremque corrupti, iusto minus quam eligendi mollitia eaque?</p>
                                    </div>
                            </div>
                            <div class="carousel-item">
                                <div class="item-img">
                                    <img src="{% static 'mainpage/img/single_cource.png' %}" alt="">
                                </div>
                                <div class="p-3">
                                    <p class="h4">¡Tips!</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima nemo quos obcaecati, a distinctio sit cum error tempore dolorum consectetur nisi! Nostrum vel veritatis accusantium recusandae maxime, tempora perferendis. Sed!</p>
                                </div>
                            </div>
                        </div>
                        <ol class="carousel-indicators">
                            <li data-target="#slide-carousel-info" data-slide-to="0" class="active"></li>
                            <li data-target="#slide-carousel-info" data-slide-to="1" class=""></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="col-lg-8 col-md-7">
            {% if not user.student.competitor_set.all %}
                <div class="su-box-common su-banner">
                    <div class="su-banner-content" style="background-image: url(http://{{ request.get_host }}{% static 'mainpage/img/advance_feature_img.png' %});">
                        <div class="text-center-sm">
                            <h4 class="text-primary">Ya puedes comenzar a buscar tutorias</h4>
                            <h5 class="text-secondary">Pudes solicitar una o compartir tus conociemintos...</h5>
                            <div class="d-flex justify-content-center justify-content-md-start">
                                <a href="#" class="btn btn-sm btn-primary waves-effect">Solicita una tutoria</a>
                                <a href="#" class="btn btn-sm btn-primary ml-2 waves-effect">Conviertete en tutor</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                {% for item in user.student.competitor_set.all %}
                    {% if item.tutorial.state == '0' %}
                        <div class="su-box-common no-padding">
                            <div class="card-header">
                                <a href="{{ item.tutorial.get_absolute_url }}" class="h4">
                                    <span>{{ item.tutorial.schedule.tutor.subject }}</span>
                                </a>
                            </div>
                            <div class="card-body">
                                <p class="card-text">
                                    <b class="text-primary">Tutor: </b><span class="text-secondary">{{ item.tutorial.schedule.tutor }}</span><br>
                                    <b class="text-primary">Día: </b><span class="text-secondary text-capitalize">{{ item.tutorial.schedule.day }}</span><br>
                                    <b class="text-primary">Hora: </b><span class="text-secondary">{{ item.tutorial.schedule.hour_start }} - {{ item.tutorial.schedule.hour_end }}</span><br>
                                </p>
                                <p class="card-text">
                                    <small class="text-muted">
                                        {{ item.tutorial.competitor_set.all.count }} estudiantes inscritos
                                    </small>
                                </p>
                                <a href="{{ item.tutorial.get_absolute_url }}" class="btn btn-info btn-block waves-effect">Detalle</a>
                            </div>
                        </div>
                    {% endif %}                                    
                {% endfor %}                            
            {% endif %}
        </div>    
    </div>
{% endblock %}

speedu_tutor/templates/speedu_tutor/layout.html
{% extends 'speedu_tutor/bootstrap4/base.html' %}

{% load static %}
{% load font_awesome %}

{% block metas %}
    <meta name="theme-color" content="#204051">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="SpeedU Tutor">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="msapplication-navbutton-color" content="#253556">    
{% endblock %}

{% block title %}{{ title }}{% endblock %}

{% block styles %}
    {% fa_css %}
    <link rel="shortcut icon" href="{% static 'mainpage/img/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'speedu_tutor/plugins/node-waves/waves.css' %}">
    <link rel="stylesheet" href="{% static 'speedu_tutor/css/style.css' %}">
    
    <link rel="manifest" href="/manifest.json">

    <link href="{% static 'mainpage/img/favicon.png' %}" rel="apple-touch-icon" sizes="60x60" type="image/png" />
    <link href="{% static 'mainpage/img/favicon.png' %}" rel="apple-touch-icon" sizes="57x57" type="image/png" />
    <link href="{% static 'mainpage/img/favicon.png' %}" rel="apple-touch-icon" sizes="72x72" type="image/png" />
    <link href="{% static 'mainpage/img/favicon.png' %}" rel="apple-touch-icon" sizes="76x76" type="image/png" />
    <link href="{% static 'mainpage/img/favicon.png' %}" rel="apple-touch-icon" sizes="114x114" type="image/png" />
    <link href="{% static 'mainpage/img/favicon.png' %}" rel="apple-touch-icon" sizes="120x120" type="image/png" />
    <link href="{% static 'mainpage/img/favicon.png' %}" rel="apple-touch-icon" sizes="144x144" type="image/png" />
    <link href="{% static 'mainpage/img/favicon.png' %}" rel="apple-touch-icon" sizes="152x152" type="image/png" />
    <link href="{% static 'mainpage/img/favicon.png' %}" rel="apple-touch-icon" sizes="180x180" type="image/png" />
    <link href="{% static 'mainpage/img/favicon.png' %}" rel="icon" sizes="192x192" type="image/png" />

    <script type="text/javascript">
        // Initialize the service worker
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.register('/serviceworker.js', {
                scope: '/' // <--- THIS BIT IS REQUIRED
            }).then(function (registration) {
                // Registration was successful
                console.log('[ServiceWorker] Rgistration successful');
            }, function (err) {
                // registration failed :(
                console.log('[ServiceWorker] registration failed');
            });
        }

    </script>

    {% block custom_styles %}{% endblock %}
{% endblock %}

{% block body_attribs %}style="margin-top: 66px; background: #eee;"{% endblock %}

{% block navbar %}
    <header>
        <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'tutor' %}">
                <img src="{% static 'mainpage/img/favicon.png' %}" alt="SpeedU logo" style="max-width: 40px;">
            </a>
            <button class="navbar-toggler waves-effect" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <ul class="navbar-user navbar-nav">
                <li class="nav-item">
                    <a href="javascript:void(0);" class="nav-link" style="font-size: 19px;">{% fa 'fa-bell' %}</a>
                </li>
            </ul> 
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tutor' %}">Inicio</a>
                    </li>
                    <li class="nav-item dropdown d-none d-md-block">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink0" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tutorias
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink0">
                            <a class="dropdown-item" href="#">{% fa 'fa-book' %} Solicitar</a>
                            <a class="dropdown-item" href="#">{% fa 'fa-pencil' %} Quiero ser tutor</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown d-none d-md-block">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Cuenta
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'profile' %}">{% fa 'fa-user' %} Perfil</a>
                            <a class="dropdown-item" href="{% url 'logout' %}">{% fa 'fa-sign-out' %} Salir</a>
                        </div>
                    </li>
                    <li class="d-block d-md-none">
                        <a href="javascript:void(0);" class="menu-toggle nav-link waves-effect waves-block">
                            <span>Tutorias</span>
                        </a>
                        <ul class="ml-menu bg-primary" style="display: none;">
                            <li class="waves-effect waves-block">
                                <a href="{% url 'profile' %}" class="nav-link">
                                    {% fa 'fa-book' %}<span class="ml-3">Solicitar</span>
                                </a>
                            </li>
                            <li class="waves-effect waves-block">
                                <a href="{% url 'logout' %}" class="nav-link">
                                    {% fa 'fa-pencil' %}<span class="ml-3">Quiero ser tutor</span>
                                </a>
                            </li>                            
                        </ul>
                    </li>
                    <li class="d-block d-md-none">
                        <a href="javascript:void(0);" class="menu-toggle nav-link waves-effect waves-block">
                            <span>Cuenta</span>
                        </a>
                        <ul class="ml-menu bg-primary" style="display: none;">
                            <li class="waves-effect waves-block">
                                <a href="{% url 'profile' %}" class="nav-link">
                                    {% fa 'fa-user' %}<span class="ml-3">Perfil</span>
                                </a>
                            </li>
                            <li class="waves-effect waves-block">
                                <a href="{% url 'logout' %}" class="nav-link">
                                    {% fa 'fa-sign-out' %}<span class="ml-3">Salir</span>
                                </a>
                            </li>                            
                        </ul>
                    </li>
                </ul>
            </div>       
        </nav>
    </header>
{% endblock %}

{% block content %}
    <div class="container main">
        <div class="row">
            <div class="col-12">
                {% block container %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'speedu_tutor/plugins/node-waves/waves.js' %}"></script>
    <script src="{% static 'speedu_tutor/plugins/jquery-slimscroll/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'speedu_tutor/js/main.js' %}"></script>

    {% block custom_scripts %}{% endblock %}
{% endblock %}

speedu_tutor/templates/speedu_tutor/profile.html
{% extends 'speedu_tutor/layout.html' %}
{% load static %}

{% block container %}
    <div class="row mt-0 mt-md-3">
        <div class="col-lg-4 col-md-5">
            <div class="user-block bg-dark">
                <div class="row row-condensed">
                    <div class="col-12">
                        <div class="user-info">
                            <div class="user-wrapper">
                                <div class="img-circle">
                                    <img src="{{ user.student.institution.image.url }}" alt="{{ user.student.institution }}" class="img">
                                </div>
                            </div>
                            <a href="{% url 'profile' %}" class="user-name h4">
                                <span>{{ user.get_full_name }}</span>
                            </a>
                            <span class="user-career">{{ user.student.career }}</span>
                        </div>
                    </div>
                </div>
                <div class="row row-condensed">
                    <div class="col-6">
                        <h4 class="text-white">{{ user.student.semester }}</h4>
                        <p class="item-data">Semestre</p>
                    </div>
                    <div class="col-6">
                        <h4 class="text-white">
                            {% if user.student.tutor and user.student.tutor.state == 'A' %}
                                Estd. Tutor
                            {% else %}
                                Estudiante
                            {% endif %}
                        </h4>
                        <p class="item-data">Rol</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-8 col-md-5">
            <div class="su-box-common no-padding">
                <div class="card-body">
                    <h5 class="card-title">Configuración de cuenta</h5>
                    <hr>
                    {% if form.errors or message.type == 'error' %}
                        <div class="alert alert-danger">
                            {{ message.text }}
                        </div>
                    {% elif message and message.type == 'success' %}
                        <div class="alert alert-success">
                            {{ message.text }}
                        </div>
                    {% endif %}
                    <div class="ml-0 ml-md-4">                        
                        <h5 class="card-title text-secondary">Cambiar contraseña</h5>
                        <form action="{% url 'profile' %}" method="post" class="mt-3" id="form_change_password">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-12 col-md-6">
                                    <label for="current_password"><small class="text-primary">Contraseña actual:</small></label>
                                    <input type="password" name="current_password" id="current_password" class="form-control"
                                    placeholder="Ingrese su contraseña actual" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-12 col-md-6">
                                    <label for="new_password"><small class="text-primary">Nueva contraseña:</small></label>
                                    <input type="password" name="new_password" id="new_password" class="form-control"
                                    placeholder="Ingrese su nueva contraseña" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-12 col-md-6">
                                    <label for="confirm_password"><small class="text-primary">Confirme la contraseña:</small></label>
                                    <input type="password" name="confirm_password" id="confirm_password" class="form-control"
                                    placeholder="Confirme su contraseña" required>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary waves-effect">Guardar cambios</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_scripts %}
    <!-- Validation Plugin Js -->
    <script src="{% static 'speedu_tutor/plugins/jquery-validation/jquery.validate.js' %}"></script>

    <!-- custom js -->
    <script src="{% static 'speedu_tutor/js/pages/profile/change-password.js' %}"></script>
{% endblock %}