mainpage/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('started/', views.started, name="get-started"),
    path('newsletter/', views.newsletter, name="newsletter"),
    path('started/get_cities/', views.get_cities, name='get-cities'),
]

speedu/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('mainpage.urls')),
    path('', include('speedu_tutor.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainpage/models.py
from django.db import models

# Models to localities

class Country(models.Model):
    name = models.CharField('Nombre del país', max_length=100, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Departament(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField('Nombre del departamento', max_length=100, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class City(models.Model):
    departament = models.ForeignKey(Departament, on_delete=models.CASCADE)
    name = models.CharField('Nombre de la ciudad', max_length=100, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Register(models.Model):
    institution = models.CharField(max_length=255, help_text='Nombre de la institución')
    name = models.CharField(max_length=100, help_text='Nombres del representante')
    lastname = models.CharField(max_length=100, help_text='Apellidos del representante')
    email = models.CharField(max_length=100, help_text='Correo de contacto')
    phone = models.IntegerField(help_text='Teléfono de contacto')
    city = models.ForeignKey(City, on_delete=models.CASCADE)

class Newsletter(models.Model):
    email = models.CharField(max_length=100, unique=True, help_text='Correo suscrito al boletín informativo')
    active = models.BooleanField(default=True, help_text='Si si establece en True se enviaran noticas del boletín...')

    def __str__(self):
        return self.email

mainpage/forms.py
from django import forms

from .models import Departament, City

class RegisterForm(forms.Form):
    DEPARTAMENT_CHOICES  = [('', '-- Elija departamento --'),] + [(d.id, d.name) for d in Departament.objects.all()]    
    CITIES_CHOICES = [(c.id, c.name) for c in City.objects.all()]

    name = forms.CharField(label='Nombres', max_length=100, required=True)
    lastname = forms.CharField(label='Apellidos', max_length=100, required=True)
    email = forms.EmailField(label='Correo Electrónico', required=True)
    phone = forms.CharField(label='Teléfono - Celular', required=True)    
    departament = forms.ChoiceField(choices=DEPARTAMENT_CHOICES)
    city = forms.ChoiceField(choices=CITIES_CHOICES)
    institution = forms.CharField(label='Institución', required=True)
    terms = forms.BooleanField(label='Acepto el acuerdo general del servicio', required=True)


class NewsletterForm(forms.Form):
    email = forms.EmailInput()

mainpage/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages

from .forms import RegisterForm, NewsletterForm
from .models import Departament, City, Newsletter, Register

def index(request):
    context = {
        'page_title': 'Inicio',
        'menu_links': {
            'home': '#home',
            'about': '#about',
            'contact': '#contact',
        },
        'scroll': True,
        'message': [str(message) for message in messages.get_messages(request)]
    }
    return render(request, 'mainpage/index.html', context=context)

def get_cities(request):
    context = {}
    if request.is_ajax() and request.method == 'GET':
        departament = Departament.objects.get(pk=request.GET['departament'])
        cities = City.objects.filter(departament=departament)
        context['cities'] = cities 
    return render(request, 'mainpage/departament/cities.html', context=context)

def started(request):    
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            lastname = form.cleaned_data['lastname']            
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            departament = form.cleaned_data['departament']
            city = form.cleaned_data['city']
            institution = form.cleaned_data['institution']            

            try:
                register = Register.objects.get(email=email)
                messages.add_message(request, messages.SUCCESS, 'Ya se ha registrado')
                messages.add_message(request, messages.SUCCESS, 
                    'Usted ya ha solicitado nuestros servicios. Por favor espere a que unos de nuestros asesores se comunique...')
            except:
                register = Register(name=name, lastname=lastname, email=email, phone=phone,
                    city=City.objects.get(pk=city), institution=institution)
                register.save()

                messages.add_message(request, messages.SUCCESS, "¡Registro exitoso!")
                messages.add_message(request, messages.SUCCESS,
                    "Gracias por elegirnos, muy pronto uno de nuestros agentes se colocará en contacto para terminar el proceso...")
            return redirect('index', permanent=True)
    else:
        form = RegisterForm()

    context = {
        'page_title': "Empezar",
        'menu_links': {
            'home': '/#home',
            'about': '/#about',
            'contact': '/#contact'
        },
        'form': form,
    }
    return render(request, 'mainpage/started.html', context=context)

def newsletter(request):       
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():       
            email = request.POST['email']
            try:
                 _last= Newsletter.objects.get(email=email)
            except Newsletter.DoesNotExist:
                _newsletter = Newsletter(email=email)
                _newsletter.save()
            
            messages.add_message(request, messages.SUCCESS, "¡Usted se ha suscrito exitosamente al boletín informativo!")
            messages.add_message(request, messages.SUCCESS, "Le mantendremos informado de todas nuestras novedades al correo "+email)
    
    return redirect('index', permanent=True)

mainpage/templates/mainpage/HTMLbase.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{{ page_title }} - SpeedU</title>
   
    <meta name="description" content="Plataforma de tutorias">
    <meta name="theme-color" content="#FFFFFF" />

    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'mainpage/css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'mainpage/css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'mainpage/css/owl.carousel.min.css' %}">
    <!-- themify CSS -->
    <link rel="stylesheet" href="{% static 'mainpage/css/themify-icons.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'mainpage/css/flaticon.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'mainpage/css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'mainpage/css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'mainpage/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'mainpage/css/custom-style.css' %}">
</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand brand-logo" href="{% url 'index' %}"> <img src="{% static 'mainpage/img/logo.png' %}" alt="SpeedU logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item justify-content-end"
                            id="navbarSupportedContent">
                            <ul class="navbar-nav align-items-center">
                                <li class="nav-item active">
                                    <a class="{% if scroll %}scroll{% endif %} nav-link" href="{{ menu_links.home }}" data-offset="0">Inicio</a>
                                </li>
                                <li class="nav-item">
                                    <a class="{% if scroll %}scroll{% endif %} nav-link" href="{{ menu_links.about }}" data-offset="10">Acerca de</a>
                                </li>
                                <li class="nav-item">
                                    <a class="{% if scroll %}scroll{% endif %} nav-link" href="{{menu_links.contact }}" data-offset="20">Contacto</a>
                                </li>
                                <li class="d-none d-lg-block">
                                    <a class="btn_1" href="{% url 'login' %}">Ingresa</a>
                                </li>
                                <li class="nav-item d-block d-lg-none">
                                    <a href="{% url 'login' %}" class="btn_1 m-0 ml-1">Ingresa</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header part end-->

    {% block content %}
    {% endblock %}

    <!-- footer part start-->
    <footer class="footer-area">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-sm-6 col-md-4 col-xl-3">
                    <div class="single-footer-widget footer_1">
                        <a href="{% url 'index' %}"> <img src="{% static 'img/logo.png' %}" alt="" class="brand-logo"> </a>
                        <p>Text</p>
                        <p>text</p>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-4">
                    <div class="single-footer-widget footer_2">
                        <h4>Boletin informativo</h4>
                        <p>Manténgase actualizado con nustras últimas tendencias
                        </p>
                        <form action="{% url 'newsletter' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="email" name="email" class="form-control" placeholder='Ingrese su email'
                                        onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Ingrese su email'" required>
                                    <div class="input-group-append">
                                        <button class="btn btn_1" type="submit"><i class="ti-angle-right"></i></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="social_icon">
                            <a href="#"> <i class="ti-facebook"></i> </a>
                            <a href="#"> <i class="ti-twitter-alt"></i> </a>
                            <a href="#"> <i class="ti-instagram"></i> </a>
                            <a href="#"> <i class="ti-skype"></i> </a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 col-md-4">
                    <div class="single-footer-widget footer_2">
                        <h4>Contact us</h4>
                        <div class="contact_info">
                            <p><span> Address :</span> Hath of it fly signs bear be one blessed after </p>
                            <p><span> Phone :</span> +2 36 265 (8060)</p>
                            <p><span> Email : </span>info@colorlib.com </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright_part_text text-center">
                        <div class="row">
                            <div class="col-lg-12">
                                <p class="footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
SpeedU Copyright &copy;<script>document.write(new Date().getFullYear());</script> Todos los derechos reservados | Esta plantilla está hecha con <i class="ti-heart" aria-hidden="true"></i> por <a href="https://colorlib.com" target="_blank">Colorlib</a>
<br>Editada por SpeedU
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer part end-->

    <!-- jquery plugins here-->
    <!-- jquery -->
    <script src="{% static 'mainpage/js/jquery-1.12.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="{% static 'mainpage/js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'mainpage/js/bootstrap.min.js' %}"></script>
    <!-- easing js -->
    <script src="{% static 'mainpage/js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'mainpage/js/swiper.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'mainpage/js/masonry.pkgd.js' %}"></script>
    <!-- particles js -->
    <script src="{% static 'mainpage/js/owl.carousel.min.js' %}"></script>
    <!--<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>-->
    <!-- swiper js -->
    <script src="{% static 'mainpage/js/slick.min.js' %}"></script>
    <script src="{% static 'mainpage/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'mainpage/js/waypoints.min.js' %}"></script>
    {% block scripts %}{% endblock %}
    <!-- custom js -->
    <script src="{% static 'mainpage/js/custom.js' %}"></script>
</body>

</html>

mainpage/templates/mainpage/started.html
{% extends 'mainpage/HTMLbase.html' %}
{% load static %}

{% block content %}
<!-- breadcrumb start-->
<section class="breadcrumb breadcrumb_bg">
  <div class="container">
      <div class="row">
          <div class="col-lg-12">
              <div class="breadcrumb_iner text-center">
                  <div class="breadcrumb_iner_item">
                      <h2>Ofrecemos la mejor experienca en tutorias</h2>
                      <p>Inicio<span>/</span>Empezar</p>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>
<!-- breadcrumb end-->

<!-- form bussines start -->
<section class="pt-5 pb-5 px-3" id="">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-12 col-lg-8">
        <div class="row">
          <div class="col-12">
            <h2 class="text-center">Registrese para comenzar</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <form class="form-contact" action="{% url 'get-started' %}" method="post">
              {% csrf_token %}
              {% if form.errors %}
                <p class="p-1 bg-danger text-center rounded text-white">                  
                    Por favor, complete o corrija los campos
                </p>
              {% endif %}
              <div class="row">
                <div class="col-sm-12 col-md-6 col-lg-6">
                  <div class="input-group mt-3">
                    {{ form.name.label_tag }}
                    <input id="id_name" type="text" class="form-control w-100 {% if form.name.errors %}border-danger{% endif %}" 
                    name="name" placeholder="Ingrese sus nombres" 
                     onfocus="this.placeholder = ''" onblur="this.placeholder='Ingrese sus nombres'">
                  </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6">
                  <div class="input-group mt-3">
                    {{ form.lastname.label_tag }}
                    <input id="id_lastname" type="text" name="lastname"
                    class="form-control w-100 {% if form.lastname.errors %}border-danger{% endif %}"
                    placeholder="Ingrese sus apellidos"  onfocus="this.placeholder=''"
                    onblur="this.placeholder='Ingrese sus apellidos'">
                  </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6">
                  <div class="input-group mt-3">
                    {{ form.email.label_tag }}
                    <input id="id_email" type="email" name="email" 
                    class="form-control w-100 {% if form.email.errors %}border-danger{% endif %}" 
                    placeholder="Ingrese su email"  onfocus="this.placeholder=''" 
                    onblur="this.placeholder='Ingrese su correo'">
                  </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6">
                  <div class="input-group mt-3">
                    {{ form.phone.label_tag }}
                    <input id="id_phone" type="text" name="phone" 
                    class="form-control w-100 {% if form.phone.errors %}border-danger{% endif %}" 
                    placeholder="Ingrese su teléfono o celular"  onfocus="this.placeholder=''" 
                    onblur="this.placeholder='Ingrese su teléfono o celular'">
                  </div>
                </div>
                <div class="col-12">
                  <div class="input-group mt-3">
                    <label>Localidad</label>
                    <div class="col-12">
                      <div class="row">
                        <div class="col-6 p-0 pr-2">
                          <select id="id_departament" 
                          class="form-control w-100 {% if form.departament.errors %}border-danger{% endif %}" 
                          name="departament" onchange="get_departament_cities()" >
                            {% for option in form.departament %}
                                {{ option }}
                            {% endfor %}
                          </select>
                        </div>
                        <div class="col-6 p-0">
                          <select class="form-control w-100 {% if form.city.errors %}border-danger{% endif %}"
                          name="city" id="id_city" >
                            <option value="">-- Elija departamento --</option>
                          </select>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-12">
                  <div class="input-group mt-3">
                    {{ form.institution.label_tag }}
                    <input id="id_institution" type="text" name="institution" 
                    class="form-control w-100 {% if form.institution.errors %}border-danger{% endif %}" 
                    placeholder="Ingrese su institución" onfocus="this.placeholder=''" 
                    onblur="this.placeholder='Ingrese su institución'">
                  </div>
                </div>
                  <div class="col-12">
                    <div class="input-group mt-3 d-flex">
                      <div class="primary-checkbox mt-1 mr-2">
                        <input type="checkbox" name="terms" id="id_terms" >
                        <label for=""></label>
                      </div>
                      <label for="id_terms" class="mb-2">Acepto el <u><a href="javascript:void(0);" style="color: #ff663b !important;"> acuerdo general del servicio</a></u></label>
                    </div>
                  </div>
              </div>
              <div class="input-group mt-3">
                <button type="submit" name="submit" class="button button-contactForm btn_1 btn-block">Registrar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- form bussines end -->

{% endblock %}

{% block scripts %}
  <script src="{% static 'mainpage/js/prototype.js' %}"></script>
{% endblock %}